services:
  phpmyadmin:
    # macで動かすためにplatformを指定
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin"
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=3306
    volumes:
      - ./phpmyadmin/sessions:/sessions
    ports:
      - 3307:80
