services:
  phpmyadmin:
    # macで動かすためにplatformを指定
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin"
    env_file:
      - .env
    volumes:
      - ./phpmyadmin/sessions:/sessions
    ports:
      - 3307:80
